### ISSUE TITLE
Save a Attachment When User Store a Post

### ISSUE THREAD

**Issue by TjandraD** [TjandraD/twittier#10]
## Description

As a user, I want to attach things to a post
- Three kinds of attachment are allowed: pictures (jpg, png, gif), video (mp4), and file (any other extensions outside of pictures and videos)

## Tasks

- [x] Create a new model to extract required variable from attachment parameter
- [x] Create a new function to check whether the attachment is null or not inside Post class
- [x] Store attachment when user save a new post

**Comment by TjandraD** [comment]
Closed with fe1ad02ae6f41d2fcd5a6fefdbb28ebd96258433
