### ISSUE TITLE
Create a proper documentation for the project

### ISSUE THREAD

**Issue by TjandraD** [TjandraD/twittier#2]
## Description
The codebase should have a readme that contains the following:
- Problem description
- Prerequisites to run the application locally
- Instructions on how to run the tests suite and the application

## To-Do
- [x] List down all of the prerequisites to run the app
- [x] Create complete instructions on how to run the tests and the app itself
- [x] Add Postman Collection to the project directory
- [ ] Additional steps: Create a contributing.md file

**Comment by TjandraD** [comment]
Since this project only having 1 contributor, I'll mark this as done
