### ISSUE TITLE
Create post text functionality

### ISSUE THREAD

**Issue by TjandraD** [TjandraD/twittier#5]
## Description

As a user, I want to post a text that might contain hashtag(s).
- Maximum limit of a text is 1000 characters
- A hashtag is a text that is followed by # symbol, for instance: #generasigigih

## Tasks
- [x] Validate Post class params when storing data
- [x] Create function inside User to store post(s)
- [x] Create a function to detect hashtag(s) inside a post
- [x] Store a new hashtag to hashtags table ( https://github.com/TjandraD/twittier/issues/6 )
- [x] Create Post controller & save post function

**Comment by TjandraD** [comment]
Closed with 3090532b2f1c09b7e6a14d8e94066d50fe83c779

**Comment by TjandraD** [comment]
Closed with 11e6a1f010b9266a51e69ec5e1b9fd5d4668c8c5
