### ISSUE TITLE
Create get posts by certain hashtag

### ISSUE THREAD

**Issue by TjandraD** [TjandraD/twittier#7]
## Description

As a user, I want to see all posts that contain a certain hashtag.
- A user can only filter by one hashtag at a time

## Tasks

- [x] Create search_post function inside Post class
- [x] Create search function inside Post controller
- [x] Add new get function inside main.rb file

**Comment by TjandraD** [comment]
Closed with c469473c208f24be43b2e2be96dc4692c9b44e89
