### ISSUE TITLE
Create Comment Function Inside Post

### ISSUE THREAD

**Issue by TjandraD** [TjandraD/twittier#9]
## Description

As a user, I want to comment on a post
- A comment can contain hashtag(s)
- A hashtag occurrence in a comment is counted in trending hashtags calculation

## Tasks

- [x] Write unit test for Post model & controller
- [x] Create insert comment function in Post model
- [x] Create insert comment method in Post controller

**Comment by TjandraD** [comment]
Closed with f3448725874e3ebfdab5a44181f97b0f57af05bb
